// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeNote(arg1:number,arg2:string):Promise<Record<string, any>>;

export function CreateNote(arg1:string,arg2:string,arg3:Array<string>):Promise<models.Note>;

export function DeleteNote(arg1:number):Promise<void>;

export function GetAllTags():Promise<Array<models.Tag>>;

export function GetBoolPreference(arg1:string,arg2:boolean):Promise<boolean>;

export function GetConfig():Promise<Record<string, any>>;

export function GetJSONPreference(arg1:string,arg2:any):Promise<void>;

export function GetNote(arg1:number):Promise<models.Note>;

export function GetPreference(arg1:string,arg2:string):Promise<string>;

export function GetStats():Promise<Record<string, any>>;

export function InitializeConfig(arg1:string,arg2:string):Promise<void>;

export function IsAutoTagAvailable():Promise<boolean>;

export function IsConfigInitialized():Promise<boolean>;

export function ListNotes(arg1:number,arg2:number):Promise<Array<models.Note>>;

export function SearchByTags(arg1:Array<string>):Promise<Array<models.Note>>;

export function SearchNotes(arg1:string,arg2:boolean,arg3:number):Promise<Array<models.Note>>;

export function SetBoolPreference(arg1:string,arg2:boolean):Promise<void>;

export function SetJSONPreference(arg1:string,arg2:any):Promise<void>;

export function SetPreference(arg1:string,arg2:string):Promise<void>;

export function ShowError(arg1:string,arg2:string):Promise<void>;

export function ShowNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ShowSuccess(arg1:string):Promise<void>;

export function SuggestTags(arg1:number):Promise<Array<string>>;

export function TestMethod():Promise<string>;

export function TestOllamaConnection():Promise<Record<string, any>>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateNote(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<models.Note>;

export function UpdateNoteTags(arg1:number,arg2:Array<string>):Promise<void>;
