// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeNote(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeNote'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2, arg3);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetBoolPreference(arg1, arg2) {
  return window['go']['main']['App']['GetBoolPreference'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetJSONPreference(arg1, arg2) {
  return window['go']['main']['App']['GetJSONPreference'](arg1, arg2);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetPreference(arg1, arg2) {
  return window['go']['main']['App']['GetPreference'](arg1, arg2);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function InitializeConfig(arg1, arg2) {
  return window['go']['main']['App']['InitializeConfig'](arg1, arg2);
}

export function IsAutoTagAvailable() {
  return window['go']['main']['App']['IsAutoTagAvailable']();
}

export function IsConfigInitialized() {
  return window['go']['main']['App']['IsConfigInitialized']();
}

export function ListNotes(arg1, arg2) {
  return window['go']['main']['App']['ListNotes'](arg1, arg2);
}

export function SearchByTags(arg1) {
  return window['go']['main']['App']['SearchByTags'](arg1);
}

export function SearchNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchNotes'](arg1, arg2, arg3);
}

export function SetBoolPreference(arg1, arg2) {
  return window['go']['main']['App']['SetBoolPreference'](arg1, arg2);
}

export function SetJSONPreference(arg1, arg2) {
  return window['go']['main']['App']['SetJSONPreference'](arg1, arg2);
}

export function SetPreference(arg1, arg2) {
  return window['go']['main']['App']['SetPreference'](arg1, arg2);
}

export function ShowError(arg1, arg2) {
  return window['go']['main']['App']['ShowError'](arg1, arg2);
}

export function ShowNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2, arg3);
}

export function ShowSuccess(arg1) {
  return window['go']['main']['App']['ShowSuccess'](arg1);
}

export function SuggestTags(arg1) {
  return window['go']['main']['App']['SuggestTags'](arg1);
}

export function TestMethod() {
  return window['go']['main']['App']['TestMethod']();
}

export function TestOllamaConnection() {
  return window['go']['main']['App']['TestOllamaConnection']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2, arg3, arg4);
}

export function UpdateNoteTags(arg1, arg2) {
  return window['go']['main']['App']['UpdateNoteTags'](arg1, arg2);
}
